name: terraform
on:
  pull_request: 
    types: [ labeled ]

jobs:
  auto-approve-pr:
    permissions:
      pull-requests: write
    if: ${{ (github.event.label.name == 'platform-eks-builder') && (github.actor == 'neeyoma') }}
    runs-on: ubuntu-latest
    steps:
      - name: Automatically approve PR
        uses: hmarr/auto-approve-action@v3
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          github-token: ${{ secrets.FPSB_PAT }}
